# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqA2tGe-CDOgmHWj0pWa3HxAVIUWSHqw

# **Business Analysis ML Model**

**load data**
"""

import pandas as pd
import os

# For local execution, specify the path to your data file
# Replace 'path/to/your/datafile.dta' with the actual path to your .dta file
filename = '2016 MSME Survey ver. 1.0 (2).dta'  # Update this path as needed
if not os.path.exists(filename):
    print(f"File '{filename}' not found. Please ensure the file exists in the current directory or update the path.")
    # Alternative: Use a sample dataset or ask user to specify the correct path
    raise FileNotFoundError(f"Data file '{filename}' not found")

df = pd.read_stata(filename)
print(f"Data loaded successfully from '{filename}'")
print(f"Dataset shape: {df.shape}")
df.head()

"""### Data Separation as x and y

"""

y=df()

# Replace 'your_target_column' with the actual name of your target variable
target_column = 'your_target_column'

# Separate features (X) and target (y)
X = df.drop(columns=[target_column])
y = df[target_column]

# Display the shapes of X and y to confirm the separation
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

# Define the output filename
output_filename = 'msme_survey.csv'

# Convert the DataFrame to a CSV file
df.to_csv(output_filename, index=False)

print(f"DataFrame successfully converted to '{output_filename}'")

# Define the target column based on our analysis
target_column = 'eh04_1' # Net income from the business per month

# Separate features (X) and target (y)
X = df.drop(columns=[target_column])
y = df[target_column]

# Display the shapes of X and y to confirm the separation
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

"""# Task
Guide me in building a model to analyze local businesses based on their products, services, sales, customers, and provide advice for growth, loss reduction, and profit margin increase using the dataset "/content/2016 MSME Survey ver. 1.0 (2).dta". The target variable for the model should be 'eh04_1' (net income).

## Data preprocessing

### Subtask:
Handle missing values, encode categorical features, and scale numerical features in the `X` DataFrame.

**Reasoning**:
Identify columns with missing values and handle them appropriately based on their data type. Then, identify categorical and numerical columns for encoding and scaling, respectively.
"""

import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify columns with missing values
missing_values_cols = X.columns[X.isnull().any()].tolist()
print("Columns with missing values:", missing_values_cols)

# Separate columns by data type
numerical_cols = X.select_dtypes(include=np.number).columns.tolist()
categorical_cols = X.select_dtypes(include='object').columns.tolist()

# Impute missing values
# Numerical columns: fill with mean
numerical_imputer = SimpleImputer(strategy='mean')
X[numerical_cols] = numerical_imputer.fit_transform(X[numerical_cols])

# Categorical columns: fill with mode
categorical_imputer = SimpleImputer(strategy='most_frequent')
X[categorical_cols] = categorical_imputer.fit_transform(X[categorical_cols])

# Verify that missing values have been handled
print("\nMissing values after imputation:", X.isnull().sum().sum())

# Identify categorical and numerical columns again after imputation
numerical_cols = X.select_dtypes(include=np.number).columns.tolist()
categorical_cols = X.select_dtypes(include='object').columns.tolist()

# Create preprocessing pipelines for numerical and categorical features
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ])

# Apply the preprocessing steps to the features
X_preprocessed = preprocessor.fit_transform(X)

# Convert the preprocessed features back to a DataFrame (optional, but useful for inspection)
# Get the feature names after one-hot encoding
onehot_feature_names = preprocessor.named_transformers_['cat']['onehot'].get_feature_names_out(categorical_cols)
all_feature_names = numerical_cols + list(onehot_feature_names)

X_preprocessed_df = pd.DataFrame(X_preprocessed, columns=all_feature_names)

display(X_preprocessed_df.head())

"""**Reasoning**:
The previous attempt to impute numerical values failed because the SimpleImputer returns a numpy array, which cannot be directly assigned back to selected columns of a pandas DataFrame. The number of columns in the imputed array did not match the number of numerical columns selected. I will fix this by using a ColumnTransformer within a Pipeline to handle both imputation and scaling for numerical features, and imputation and encoding for categorical features, ensuring the output is a single preprocessed array.


"""

import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Separate columns by data type
numerical_cols = X.select_dtypes(include=np.number).columns.tolist()
categorical_cols = X.select_dtypes(include='object').columns.tolist()

# Create preprocessing pipelines for numerical and categorical features
# Numerical pipeline: impute with mean and then scale
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

# Categorical pipeline: impute with most frequent and then one-hot encode
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ],
    remainder='passthrough' # Keep other columns (if any) - although not expected here
)

# Apply the preprocessing steps to the features
X_preprocessed = preprocessor.fit_transform(X)

# Get the feature names after one-hot encoding
onehot_feature_names = preprocessor.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_cols)
all_feature_names = numerical_cols + list(onehot_feature_names)

X_preprocessed_df = pd.DataFrame(X_preprocessed, columns=all_feature_names)

display(X_preprocessed_df.head())

"""**Reasoning**:
The error "ValueError: scipy.sparse does not support dtype object" indicates that after imputation, some categorical columns might still have an object dtype that cannot be handled by the sparse matrix format used by the ColumnTransformer's `hstack` method. This could be due to an issue with the `SimpleImputer` when dealing with mixed types or specific values in the categorical columns. To address this, I will explicitly convert the categorical columns to string type before applying the imputer and one-hot encoder. This ensures that the data type is consistent and compatible with the subsequent transformations.


"""

import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import pandas as pd # Import pandas

# Separate columns by data type
numerical_cols = X.select_dtypes(include=np.number).columns.tolist()
categorical_cols = X.select_dtypes(include='object').columns.tolist()

# Convert categorical columns to string type to avoid dtype issues
for col in categorical_cols:
    X[col] = X[col].astype(str)


# Create preprocessing pipelines for numerical and categorical features
# Numerical pipeline: impute with mean and then scale
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

# Categorical pipeline: impute with most frequent and then one-hot encode
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a column transformer to apply different transformations to different columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ],
    remainder='passthrough' # Keep other columns (if any) - although not expected here
)

# Apply the preprocessing steps to the features
X_preprocessed = preprocessor.fit_transform(X)

# Get the feature names after one-hot encoding
onehot_feature_names = preprocessor.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_cols)
all_feature_names = numerical_cols + list(onehot_feature_names)

X_preprocessed_df = pd.DataFrame(X_preprocessed, columns=all_feature_names)

display(X_preprocessed_df.head())

"""**Reasoning**:
The error persists even after converting categorical columns to string type. This suggests that the issue might be within the categorical columns themselves, possibly due to some values that are not compatible with one-hot encoding even after conversion to string and imputation. A potential cause could be columns with no non-missing values (as indicated by the UserWarning about skipping 'ef03_12'), or columns with mixed types that are not being handled correctly by the imputer or encoder despite the `astype(str)`. To further investigate and address this, I will inspect the unique values and data types within the categorical columns after the initial string conversion and imputation, particularly focusing on columns that might be causing issues. I will then refine the preprocessing based on the findings, potentially removing problematic columns or handling them differently if necessary.


"""

# Inspect unique values and data types in categorical columns after string conversion
for col in categorical_cols:
    print(f"Column: {col}, Dtype: {X[col].dtype}")
    print(f"Unique values sample for {col}: {X[col].unique()[:10]}") # Display first 10 unique values

# Re-run the preprocessing pipeline with a potential fix for object dtype issue in sparse matrix
# This might involve identifying and excluding columns that cause the error,
# or trying a different approach for handling them.
# Based on the error and previous attempts, it seems there might be a specific issue
# with how one-hot encoding interacts with the imputed string data in some columns.
# Let's try to exclude the column 'ef03_12' which was mentioned in the warning as it has no non-missing values.
# This might not be the direct cause of the Value Error but it's a good practice to handle such columns.

if 'ef03_12' in numerical_cols:
    numerical_cols.remove('ef03_12')

# Re-create preprocessing pipelines
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)
    ],
    remainder='passthrough'
)

# Apply preprocessing
X_preprocessed = preprocessor.fit_transform(X)

# Get feature names and create DataFrame
onehot_feature_names = preprocessor.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_cols)
all_feature_names = numerical_cols + list(onehot_feature_names)

X_preprocessed_df = pd.DataFrame(X_preprocessed, columns=all_feature_names)

display(X_preprocessed_df.head())

"""**Reasoning**:
The inspection of categorical columns showed that some columns have mixed types or values that might still be causing issues with the sparse matrix conversion during one-hot encoding. The error persists even after converting to string and attempting to handle a column with no non-missing values. A more robust approach is to explicitly identify and handle columns that are not purely numerical or suitable for one-hot encoding with sparse output. I will check the unique values of each categorical column again and if a column has a very large number of unique values (potentially indicating identifier-like data or free-text), or if it still causes dtype issues after imputation, I will exclude it from the one-hot encoding process. For columns with a manageable number of unique values suitable for one-hot encoding, I will ensure they are processed correctly. Given the nature of the dataset, 'key3' and 'key2' likely fall into the identifier category and should be excluded. I will refine the categorical column selection based on this observation and re-run the preprocessing.


"""

# Exclude identifier columns that are not suitable for one-hot encoding
categorical_cols_to_encode = [col for col in categorical_cols if col not in ['key3', 'key2']]

# Create preprocessing pipelines for numerical and selected categorical features
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a column transformer with the refined list of categorical columns
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols_to_encode)
    ],
    remainder='passthrough' # Keep other columns (like key3, key2) as is for now
)

# Apply the preprocessing steps to the features
# Convert to dense array to avoid scipy.sparse object dtype issue if it arises from onehotencoder output
X_preprocessed = preprocessor.fit_transform(X).todense()


# Get the feature names after one-hot encoding
onehot_feature_names = preprocessor.named_transformers_['cat'].named_steps['onehot'].get_feature_names_out(categorical_cols_to_encode)
# Get the names of the columns that were passed through
passthrough_cols = [col for col in X.columns if col not in numerical_cols and col not in categorical_cols_to_encode]
all_feature_names = numerical_cols + list(onehot_feature_names) + passthrough_cols


X_preprocessed_df = pd.DataFrame(X_preprocessed, columns=all_feature_names)

display(X_preprocessed_df.head())

"""**Reasoning**:
The error persists even after excluding 'key3' and 'key2' and converting to dense array, indicating that the issue with the object dtype is still present within the columns being transformed by the `ColumnTransformer` before the `.todense()` call. This is likely due to some problematic values or dtypes within the remaining categorical columns after imputation. To pinpoint the exact issue, I will isolate the categorical transformation step and inspect its output before combining with numerical features. I will apply the categorical pipeline independently and check the dtype of the resulting sparse matrix. This will help determine if the issue is with the one-hot encoding step producing an unsupported dtype. If the issue is confirmed in the categorical output, I will need to investigate the specific categorical columns and their unique values more thoroughly to find the problematic ones or values that are not being handled correctly by the one-hot encoder. I will also convert the output of the categorical transformer to a dense array before combining with the numerical features to avoid potential issues with `sparse.hstack` if the issue is in the combination step.


"""

# Isolate and apply the categorical transformation
categorical_transformer.fit(X[categorical_cols_to_encode])
X_categorical_preprocessed_sparse = categorical_transformer.transform(X[categorical_cols_to_encode])

# Check the dtype of the sparse output from the categorical transformer
print("Dtype of categorical preprocessed sparse output:", X_categorical_preprocessed_sparse.dtype)

# Convert the categorical sparse output to a dense array
X_categorical_preprocessed_dense = X_categorical_preprocessed_sparse.todense()

# Apply the numerical transformation
numerical_transformer.fit(X[numerical_cols])
X_numerical_preprocessed = numerical_transformer.transform(X[numerical_cols])

# Concatenate the preprocessed numerical and categorical features (now both dense)
X_preprocessed = np.hstack((X_numerical_preprocessed, X_categorical_preprocessed_dense))

# Get feature names and create DataFrame
onehot_feature_names = categorical_transformer.named_steps['onehot'].get_feature_names_out(categorical_cols_to_encode)
all_feature_names = numerical_cols + list(onehot_feature_names)

X_preprocessed_df = pd.DataFrame(X_preprocessed, columns=all_feature_names)

display(X_preprocessed_df.head())

"""## Split data

### Subtask:
Split the preprocessed data into training and testing sets.

**Reasoning**:
Split the preprocessed data into training and testing sets and print their shapes.
"""

from sklearn.model_selection import train_test_split

# Split the preprocessed data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_preprocessed_df, y, test_size=0.2, random_state=42)

# Print the shapes of the resulting sets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

"""## Model selection

### Subtask:
Choose a suitable regression model for your task. We can start with a common choice like a Linear Regression or a more robust model like a RandomForestRegressor.

**Reasoning**:
Considering the large number of features after one-hot encoding and the potential for non-linear relationships, a RandomForestRegressor is a suitable choice. It can handle complex interactions and is less susceptible to multicollinearity compared to linear models. It also provides feature importance, which can be useful for understanding the factors influencing net income. I will import the necessary model from scikit-learn.
"""

from sklearn.ensemble import RandomForestRegressor

"""## Model training

### Subtask:
Train the selected RandomForestRegressor model on the training data.

**Reasoning**:
Train the RandomForestRegressor model using the training data.
"""

# Instantiate a RandomForestRegressor object
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

# Train the model
model.fit(X_train, y_train)

"""**Reasoning**:
The traceback indicates that the target variable `y_train` contains NaN values, which the RandomForestRegressor cannot handle directly. I need to handle these missing values in `y_train` before training the model. Since this is a regression task, I will impute the missing values with the mean of `y_train`.


"""

import numpy as np
from sklearn.ensemble import RandomForestRegressor

# Impute missing values in y_train with the mean
y_train_imputed = y_train.fillna(y_train.mean())

# Instantiate a RandomForestRegressor object
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

# Train the model using the imputed y_train data
model.fit(X_train, y_train_imputed)

"""## Model evaluation

### Subtask:
Evaluate the performance of the trained model on the testing data using appropriate regression metrics (e.g., Mean Absolute Error, Mean Squared Error, R-squared).

**Reasoning**:
Evaluate the trained model's performance on the test set using regression metrics.
"""

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Make predictions on the test set
y_pred = model.predict(X_test)

# Calculate evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse) # Calculate RMSE as well for better interpretability
r2 = r2_score(y_test, y_pred)

# Print the calculated metrics
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R2): {r2}")

"""**Reasoning**:
The error indicates that `y_test` contains NaN values. I need to handle these missing values in `y_test` before calculating the evaluation metrics, similar to how missing values in `y_train` were handled.


"""

# Impute missing values in y_test with the mean of y_test
y_test_imputed = y_test.fillna(y_test.mean())

# Calculate evaluation metrics using the imputed y_test
mae = mean_absolute_error(y_test_imputed, y_pred)
mse = mean_squared_error(y_test_imputed, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test_imputed, y_pred)

# Print the calculated metrics
print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")
print(f"R-squared (R2): {r2}")

"""## Model interpretation (optional but recommended)

### Subtask:
Explore feature importance to understand which factors most influence net income.

**Reasoning**:
Access the feature_importances_ attribute of the trained model, create a Pandas Series from the feature importances, using the column names of X_train as the index, sort the feature importances in descending order, and display the top 20 most important features.
"""

import pandas as pd
import matplotlib.pyplot as plt

# Access feature importances from the trained model
feature_importances = model.feature_importances_

# Create a Pandas Series with feature names as index
feature_importance_series = pd.Series(feature_importances, index=X_train.columns)

# Sort feature importances in descending order
sorted_feature_importances = feature_importance_series.sort_values(ascending=False)

# Display the top 20 most important features
print("Top 20 Most Important Features:")
print(sorted_feature_importances.head(20))

# Visualize the top 20 most important features
plt.figure(figsize=(10, 8))
sorted_feature_importances.head(20).plot(kind='bar')
plt.title('Top 20 Most Important Features')
plt.xlabel('Features')
plt.ylabel('Importance')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""## Prediction and advice generation

### Subtask:
Use the trained model to make predictions and generate insights or advice for businesses based on the model's output and feature importance.

**Reasoning**:
Use the trained model to make predictions on the test data, create a DataFrame with actual, predicted, and difference values, and then generate insights and advice based on the analysis of predictions and feature importance.
"""

# Make predictions on the test data
y_pred = model.predict(X_test)

# Create a DataFrame for analysis
predictions_df = pd.DataFrame({'Actual': y_test_imputed, 'Predicted': y_pred})
predictions_df['Difference'] = predictions_df['Actual'] - predictions_df['Predicted']

# Display the predictions DataFrame head
print("Predictions DataFrame Head:")
display(predictions_df.head())

# Analyze instances with significant deviations (e.g., difference > 2 * MAE)
significant_deviations = predictions_df[abs(predictions_df['Difference']) > 2 * mae]
print(f"\nInstances with significant deviations (Difference > 2 * MAE = {2 * mae:.2f}):")
display(significant_deviations.head())


# --- Generating Insights and Advice ---

print("\n--- General Advice based on Top Feature Importances ---")
# Access the top features from the previous step
top_features = sorted_feature_importances.head(10) # Consider top 10 for advice

print("Based on the model, the most important factors influencing net income include:")
for feature, importance in top_features.items():
    print(f"- {feature} (Importance: {importance:.4f})")

print("\nGeneral Advice for Businesses:")
print("- Focus on improving aspects related to these key features.")
print("- For example, if 'eh15_1' (related to sales/revenue) is important, explore strategies to increase sales.")
print("- If 'eg11_1' (related to expenses) is important, look for ways to optimize costs.")
print("- Investigate what these specific features represent in the original data dictionary for targeted actions.")

print("\n--- Tailored Advice based on Model Predictions ---")
print("How to use predictions for tailored advice:")

print("\nFor businesses with low predicted net income:")
print("- Analyze their specific feature values compared to the average or successful businesses.")
print("- Identify areas where they underperform on important features.")
print("- Recommend targeted improvements based on those specific feature weaknesses (e.g., improving marketing if 'marketing expenses' is a relevant important feature and their value is low).")

print("\nFor businesses with high predicted net income:")
print("- Analyze their specific feature values to understand their strengths.")
print("- Recommend strategies for growth and scaling based on their successful areas (e.g., expanding operations if 'number of employees' is an important feature and their value is high).")
print("- Encourage them to continue focusing on the factors contributing to their high income.")

print("\nNote: To provide truly tailored advice, you would need to analyze individual business profiles (rows in the DataFrame) in detail, considering their specific predicted income and feature values.")

"""## Summary:

### Data Analysis Key Findings

*   The initial data preprocessing steps faced challenges with handling missing values and ensuring compatibility between categorical data, imputation, and one-hot encoding, particularly when aiming for a sparse matrix output. Converting the sparse output of the categorical transformer to a dense array before concatenation resolved these issues.
*   The preprocessed data, with numerical features scaled and categorical features one-hot encoded, was successfully split into training and testing sets, with 80% for training and 20% for testing.
*   A RandomForestRegressor model was chosen for its ability to handle complex interactions and provide feature importance insights.
*   Training the RandomForestRegressor required imputing missing values in the target variable (`y_train`) with its mean, as the model does not inherently handle NaNs in the target.
*   Model evaluation on the testing data, after imputing missing values in `y_test` with its mean, yielded an R-squared score of approximately 0.939, indicating a strong fit. The MAE was around \$311,262 and the RMSE was about \$5,312,451, suggesting the presence of some larger prediction errors.
*   Feature importance analysis revealed that features like `eh15_1`, `eg11_1`, `eg24_1`, `ej18_2`, and `eg21_1` are among the most influential factors affecting net income.

### Insights or Next Steps

*   Investigate the specific meanings of the top influential features (`eh15_1`, `eg11_1`, `eg24_1`, `ej18_2`, `eg21_1`, etc.) using the original data dictionary to provide more concrete and actionable advice related to sales, expenses, or other relevant business aspects.
*   Develop a more sophisticated approach for identifying businesses with significant prediction deviations (large differences between actual and predicted net income) and analyze their specific characteristics to understand why the model struggles with these instances, potentially leading to improved model performance or tailored intervention strategies.

"""